import { Movie } from "./types";

export const mockMovies: Movie[] = [
  {
    id: "m1",
    title: "Drishyam 3",
    language: "Malayalam",
    platform: "Prime Video",
    platformLogo: "/platforms/prime.png",
    genre: ["Thriller", "Drama"],
    releaseDate: "2026-08-15",
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=800",
    description: "Georgekutty and his family are back. Will they manage to escape the law once again or will the truth finally come to light?",
    cast: ["Mohanlal", "Meena", "Ansiba Hassan", "Esther Anil"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://primevideo.com",
    trending: true,
    searched: 15420,
  },
  {
    id: "t1",
    title: "Leo 2: The Return",
    language: "Tamil",
    platform: "Netflix",
    platformLogo: "/platforms/netflix.png",
    genre: ["Action", "Thriller"],
    releaseDate: "2026-10-19",
    posterUrl: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&q=80&w=800",
    description: "Parthiban's past catches up to him once more as a new wave of gangsters enter his life, forcing him to unleash his alter ego.",
    cast: ["Thalapathy Vijay", "Trisha", "Sanjay Dutt"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://netflix.com",
    trending: true,
    searched: 25000,
  },
  {
    id: "h1",
    title: "Jawan: The Next Chapter",
    language: "Hindi",
    platform: "Netflix",
    platformLogo: "/platforms/netflix.png",
    genre: ["Action", "Drama"],
    releaseDate: "2026-09-07",
    posterUrl: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=800",
    description: "An emotional journey of a man set to rectify wrongs in the society, driven by a personal vendetta while keeping a promise to his country.",
    cast: ["Shah Rukh Khan", "Nayanthara", "Deepika Padukone"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://netflix.com",
    trending: false,
    searched: 12050,
  },
  {
    id: "m2",
    title: "Manjummel Boys 2",
    language: "Malayalam",
    platform: "Hotstar",
    platformLogo: "/platforms/hotstar.png",
    genre: ["Comedy", "Thriller"],
    releaseDate: "2026-05-20",
    posterUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&q=80&w=800",
    description: "The boys are back on another unplanned trip, but this time, the adventure is wilder and the stakes are much more comedic yet thrilling.",
    cast: ["Soubin Shahir", "Sreenath Bhasi", "Balu Varghese"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://hotstar.com",
    trending: true,
    searched: 18000,
  },
  {
    id: "h2",
    title: "Farzi Season 2",
    language: "Hindi",
    platform: "Prime Video",
    platformLogo: "/platforms/prime.png",
    genre: ["Thriller", "Action"],
    releaseDate: "2026-06-11",
    posterUrl: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800",
    description: "Sunny's counterfeit empire expands, while Michael's obsession to capture him takes them both down a chaotic spiral.",
    cast: ["Shahid Kapoor", "Vijay Sethupathi", "Kay Kay Menon"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://primevideo.com",
    trending: false,
    searched: 13400,
  },
  {
    id: "t2",
    title: "Kanguva",
    language: "Tamil",
    platform: "SonyLIV",
    platformLogo: "/platforms/sonyliv.png",
    genre: ["Action", "Drama"],
    releaseDate: "2026-04-14",
    posterUrl: "https://images.unsplash.com/photo-1616530940355-351fabd9524b?auto=format&fit=crop&q=80&w=800",
    description: "A mighty warrior in 1678 dies unexpectedly due to a disease. Centuries later, researchers try to uncover the mysteries surrounding his era.",
    cast: ["Suriya", "Bobby Deol", "Disha Patani"],
    trailerUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    watchUrl: "https://sonyliv.com",
    trending: false,
    searched: 9500,
  }
];

export const LANGUAGES = ["All", "Malayalam", "Tamil", "Hindi", "English"];
export const PLATFORMS = ["All", "Netflix", "Prime Video", "Hotstar", "SonyLIV", "Zee5"];
export const GENRES = ["All", "Action", "Thriller", "Comedy", "Drama", "Romance"];
